### PR TITLE
Solution fix

### PR DESCRIPTION
**Pull request by aturkewi**
Updated gem file to include jekyll

Updated spec so that path to pages being scraped now looks in /fixtures/student-site

@pletcher @PeterBell

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @aturkewi looks like you added a lot more than you described in the comments above. Were all the additions to the code deliberate? Just want to check...

**Comment by aturkewi** [comment]
@PeterBell You're right, I should have added a better note here. I actually just merged the master into the solution and just kept all the solution files. This merge ALSO brings the solution branch up to date with the master branch.

**Comment by PeterBell** [comment]
Hey @aturkewi but it looks to me like this is a PR to merge into master, so all those solution files would become part of the *master* branch - was that intended? If you want to make some changes to master and some to the solution branch you'd have to have two separate PR's, one to merge the additions into master and the other for the additions into the solution branch . . . ping me in the am if you want to go through this!

**Comment by aturkewi** [comment]
@PeterBell too right you are. I'm going to close this PR (remove the changes to the Gemlock.file), and then make a new PR to the solution branch. 

Sorry about that.

**Pull request closed without merging**
